before_script:
  - rm -rf "*-env"; virtualenv -p python3 ${CI_JOB_ID}-env
  - rm -rf ../mod_global_trajectory
  - ${CI_JOB_ID}-env/bin/pip3 install -r requirements.txt

after_script:
  - 'killall --user $USER'
  - rm -rf ${CI_JOB_ID}-env

.internal_models_template: &internal_models_template
- 'git clone --single-branch --branch develop https://ga76dol:${Global_Traj_Token}@gitlab.lrz.de/roborace/modules/mod_global_trajectory.git ../mod_global_trajectory'
- ${CI_JOB_ID}-env/bin/pip3 install -r ../mod_global_trajectory/requirements.txt

.external_models_template: &external_models_template
- 'git submodule update --recursive --init'

.acados_template: &acados_template
- ${CI_JOB_ID}-env/bin/pip3 install /home/$USER/acados/interfaces/acados_template
- 'wget https://github.com/acados/tera_renderer/releases/download/v0.0.34/t_renderer-v0.0.34-linux'
- 'mkdir -p /home/$USER/acados/bin/'
- 'cp t_renderer-v0.0.34-linux /home/$USER/acados/bin/t_renderer'
- 'chmod +x /home/$USER/acados/bin/t_renderer'
- 'export ACADOS_SOURCE_DIR=/home/$USER/acados'
- 'export LD_LIBRARY_PATH=/home/$USER/acados/lib:$LD_LIBRARY_PATH'

stages:
  - opt_v_ref
  - opt_online
  - opt_v_ref_external
  - opt_online_external
  - deploy_external

VRef_MNT:
  stage: opt_v_ref
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - *internal_models_template
    - *acados_template
    # Send ZMQ message to main script
    - (${CI_JOB_ID}-env/bin/python3 ci/opt_v_ref_mnt.py> /dev/null) &
    # Start main script
    - ${CI_JOB_ID}-env/bin/python3 main_emb_es.py 1
  allow_failure: false
  timeout: 10 min
  artifacts:
    when: always
    paths:
      - v_ref.csv

OptOnline_MNT:
  stage: opt_online
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - *internal_models_template
    - *acados_template
    # Send ZMQ message to main script
    - (${CI_JOB_ID}-env/bin/python3 ci/opt_online_mnt.py> /dev/null) &
    # Start main script
    - ${CI_JOB_ID}-env/bin/python3 main_emb_es.py 1
  allow_failure: false
  timeout: 10 min
  dependencies:
    - VRef_MNT

VRef_MOD:
  stage: opt_v_ref
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - *internal_models_template
    - *acados_template
    # Send ZMQ message to main script
    - (${CI_JOB_ID}-env/bin/python3 ci/opt_v_ref_mod.py> /dev/null) &
    # Start main script
    - ${CI_JOB_ID}-env/bin/python3 main_emb_es.py 1
  allow_failure: false
  timeout: 10 min
  artifacts:
    when: always
    paths:
      - v_ref.csv

OptOnline_MOD:
  stage: opt_online
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - *internal_models_template
    - *acados_template
    # Send ZMQ message to main script
    - (${CI_JOB_ID}-env/bin/python3 ci/opt_online_mod.py> /dev/null) &
    # Start main script
    - ${CI_JOB_ID}-env/bin/python3 main_emb_es.py 1
  allow_failure: false
  timeout: 10 min
  dependencies:
    - VRef_MOD

VRef_BER:
  stage: opt_v_ref
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - *internal_models_template
    - *acados_template
    # Send ZMQ message to main script
    - (${CI_JOB_ID}-env/bin/python3 ci/opt_v_ref_ber.py> /dev/null) &
    # Start main script
    - ${CI_JOB_ID}-env/bin/python3 main_emb_es.py 1
  allow_failure: false
  timeout: 10 min
  artifacts:
    when: always
    paths:
      - v_ref.csv

OptOnline_BER:
  stage: opt_online
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - *internal_models_template
    - *acados_template
    # Send ZMQ message to main script
    - (${CI_JOB_ID}-env/bin/python3 ci/opt_online_ber.py> /dev/null) &
    # Start main script
    - ${CI_JOB_ID}-env/bin/python3 main_emb_es.py 1
  allow_failure: false
  timeout: 10 min
  dependencies:
    - VRef_BER

VRef_MNT_external:
  stage: opt_v_ref_external
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - *external_models_template
    - *acados_template
    # Send ZMQ message to main script
    - (${CI_JOB_ID}-env/bin/python3 ci/opt_v_ref_mnt.py> /dev/null) &
    # Start main script
    - ${CI_JOB_ID}-env/bin/python3 main_emb_es.py 1
  allow_failure: false
  timeout: 10 min
  artifacts:
    when: always
    paths:
      - v_ref.csv

OptOnline_MNT_external:
  stage: opt_online_external
  tags:
    - CI_TrackPerformanceLRZ
  script:
    - *external_models_template
    - *acados_template
    # Send ZMQ message to main script
    - (${CI_JOB_ID}-env/bin/python3 ci/opt_online_mnt.py> /dev/null) &
    # Start main script
    - ${CI_JOB_ID}-env/bin/python3 main_emb_es.py 1
  allow_failure: false
  timeout: 10 min
  dependencies:
    - VRef_MNT_external

pages:
  stage: deploy_external
  tags:
    - CI_TrackPerformanceLRZ
  only:
    - master
  script:
    - *acados_template
    - ${CI_JOB_ID}-env/bin/pip3 install Sphinx>=3.1.1
    - ${CI_JOB_ID}-env/bin/pip3 install sphinx-rtd-theme>=0.5.0
    - ${CI_JOB_ID}-env/bin/pip3 install sphinx-automodapi
    - ${CI_JOB_ID}-env/bin/pip3 install alabaster>=0.7.12
    - ${CI_JOB_ID}-env/bin/sphinx-apidoc -f -o ./docs/source .
    - ${CI_JOB_ID}-env/bin/sphinx-build -b html docs/source docs/build
    - mkdir public
    - cp -r docs/build/* public
  artifacts:
    when: always
    paths:
      - public
  allow_failure: false
